### ISSUE TITLE
SRV records

### ISSUE THREAD

**Issue by ferdi-vissers** [phallstrom/AlfredDig#2]
Hi Philip,

First of all, thank you for creating the dig script, very handy if you are a alfred user.

Next to A and MX records I also need to check regally SRV records to see if the correct h323 and sip records are available. do you see any change to ad that to your script?

regards, Ferdi

**Comment by phallstrom** [comment]
You can currently just do `dig example.com srv ` and it will query those records. If you want to make it do that by default you'd need to tweak the script.
